name: Code Quality (gofmt, gotest)
on: [pull_request]

jobs:
  unittest:
    if: github.event_name == 'pull_request'
    name: Code Quality (gofmt, gotest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18.x
      - name: Test 
        run: go test ./...

  docker build:
    if: github.event_name == 'pull_request'
    name: Code Quality (gofmt, gotest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: docker build
        run: docker build -t rss_checker:latest .